disabled_rules:
  - trailing_whitespace
  - nesting
  - type_body_length
  - cyclomatic_complexity
  - line_length
  - statement_position
  - identifier_name
  - todo
  - function_parameter_count
  - function_body_length
  - large_tuple
  - class_delegate_protocol
  - notification_center_detachment
  - multiple_closures_with_trailing_closure
  - xctfail_message
  - opening_brace
  - closure_end_indentation
  - superfluous_disable_command
  
opt_in_rules:
  - weak_delegate
  - file_header
  - attributes
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  # - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  # - file_name
  - first_where
  # - force_unwrapping
  #- implicit_return
  - joined_default_parameter
  - modifier_order
  #- multiline_arguments
  - multiline_parameters
  # - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  # - override_in_extension
  - private_action
  - prohibited_super_call
  - redundant_type_annotation
  - required_enum_case
  - sorted_imports
  # - unavailable_function
  - unneeded_parentheses_in_closure_argument
  
type_body_length:
  warning: 300 # warning
  error: 400 # error
  
file_length:
  warning: 900
  error: 1200

type_name:
  min_length: 2
  max_length:
    warning: 60
    error: 100
  
excluded:
  - Pods
  - MeeticInbox/Externals/Giphy
  - MeeticInbox/MeeticInbox/Externals/Giphy
  - Scripts
  - Meetic*/Generated
  - Meetic*/Meetic*/Generated
  - Meetic/Application/Generated
  - MeeticLara/MeeticLara/Generated

force_cast: warning
force_try: warning
